/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkoutsHistoryImport } from './routes/workoutsHistory'
import { Route as IndexImport } from './routes/index'
import { Route as EditSetExerciseImport } from './routes/editSet/$exercise'

// Create/Update Routes

const WorkoutsHistoryRoute = WorkoutsHistoryImport.update({
  id: '/workoutsHistory',
  path: '/workoutsHistory',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditSetExerciseRoute = EditSetExerciseImport.update({
  id: '/editSet/$exercise',
  path: '/editSet/$exercise',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/workoutsHistory': {
      id: '/workoutsHistory'
      path: '/workoutsHistory'
      fullPath: '/workoutsHistory'
      preLoaderRoute: typeof WorkoutsHistoryImport
      parentRoute: typeof rootRoute
    }
    '/editSet/$exercise': {
      id: '/editSet/$exercise'
      path: '/editSet/$exercise'
      fullPath: '/editSet/$exercise'
      preLoaderRoute: typeof EditSetExerciseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workoutsHistory': typeof WorkoutsHistoryRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workoutsHistory': typeof WorkoutsHistoryRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/workoutsHistory': typeof WorkoutsHistoryRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workoutsHistory' | '/editSet/$exercise'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workoutsHistory' | '/editSet/$exercise'
  id: '__root__' | '/' | '/workoutsHistory' | '/editSet/$exercise'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutsHistoryRoute: typeof WorkoutsHistoryRoute
  EditSetExerciseRoute: typeof EditSetExerciseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutsHistoryRoute: WorkoutsHistoryRoute,
  EditSetExerciseRoute: EditSetExerciseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/workoutsHistory",
        "/editSet/$exercise"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/workoutsHistory": {
      "filePath": "workoutsHistory.tsx"
    },
    "/editSet/$exercise": {
      "filePath": "editSet/$exercise.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
