/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkoutsHistoryWorkoutsHistoryImport } from './routes/workoutsHistory/workoutsHistory'
import { Route as EditSetExerciseImport } from './routes/editSet/$./routes/workoutsHistory/workoutsHistory'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutsHistoryWorkoutsHistoryRoute =
  WorkoutsHistoryWorkoutsHistoryImport.update({
    id: '/workoutsHistory/workoutsHistory',
    path: '/workoutsHistory/workoutsHistory',
    getParentRoute: () => rootRoute,
  } as any)

const EditSetExerciseRoute = EditSetExerciseImport.update({
  id: '/editSet/$exercise',
  path: '/editSet/$exercise',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editSet/$exercise': {
      id: '/editSet/$exercise'
      path: '/editSet/$exercise'
      fullPath: '/editSet/$exercise'
      preLoaderRoute: typeof EditSetExerciseImport
      parentRoute: typeof rootRoute
    }
    '/workoutsHistory/workoutsHistory': {
      id: '/workoutsHistory/workoutsHistory'
      path: '/workoutsHistory/workoutsHistory'
      fullPath: '/workoutsHistory/workoutsHistory'
      preLoaderRoute: typeof WorkoutsHistoryWorkoutsHistoryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
  '/workoutsHistory/workoutsHistory': typeof WorkoutsHistoryWorkoutsHistoryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
  '/workoutsHistory/workoutsHistory': typeof WorkoutsHistoryWorkoutsHistoryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editSet/$exercise': typeof EditSetExerciseRoute
  '/workoutsHistory/workoutsHistory': typeof WorkoutsHistoryWorkoutsHistoryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editSet/$exercise' | '/workoutsHistory/workoutsHistory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editSet/$exercise' | '/workoutsHistory/workoutsHistory'
  id:
    | '__root__'
    | '/'
    | '/editSet/$exercise'
    | '/workoutsHistory/workoutsHistory'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditSetExerciseRoute: typeof EditSetExerciseRoute
  WorkoutsHistoryWorkoutsHistoryRoute: typeof WorkoutsHistoryWorkoutsHistoryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditSetExerciseRoute: EditSetExerciseRoute,
  WorkoutsHistoryWorkoutsHistoryRoute: WorkoutsHistoryWorkoutsHistoryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editSet/$exercise",
        "/workoutsHistory/workoutsHistory"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editSet/$exercise": {
      "filePath": "editSet/$exercise.tsx"
    },
    "/workoutsHistory/workoutsHistory": {
      "filePath": "workoutsHistory/workoutsHistory.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
